local MapEvent = {}

MapEvent.OBJECT_IN_HATRED_RANGE = "hatred"
MapEvent.OBJECT_IN_ATTACK_RANGE = "attack"

MapEvent.EVENT_MONSTER_DEAD = "EVENT_MONSTER_DEAD"
MapEvent.EVENT_NINJA_TRUEDAMAGE = "EVENT_NINJA_TRUEDAMAGE"


return MapEvent