local MapEvent = {}

MapEvent.OBJECT_IN_HATRED_RANGE = "hatred"
MapEvent.OBJECT_IN_ATTACK_RANGE = "attack"

MapEvent.EVENT_MONSTER_DEAD = "EVENT_MONSTER_DEAD"
MapEvent.EVENT_PLAYER_CURE = "EVENT_PLAYER_CURE"
MapEvent.EVENT_PLAYER_SICK = "EVENT_PLAYER_SICK"


return MapEvent